name: build-push

on:
  push:
    branches:
    - 'main'

jobs:
  imagetag:
    outputs:
      version: ${{ steps.extracttag.outputs.tag }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Extract the image version
      id: extracttag
      run: |
        echo "::set-output name=tag::$(awk -F: '/^FROM/ { print $2 }' Dockerfile)"
  docker:
    runs-on: ubuntu-latest
    needs: imagetag
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/amazeeio/opensearch:${{ needs.imagetag.outputs.version }}
