name: build

on: pull_request

jobs:
  imagetag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extracttag.outputs.tag }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Extract the image version
      id: extracttag
      run: |
        echo "tag=$(awk -F: '/^FROM/ { print $2 }' Dockerfile)" >> $GITHUB_OUTPUT
  build-push:
    runs-on: ubuntu-latest
    needs: imagetag
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: ${{ github.actor != 'dependabot[bot]' }} # don't push dependabot PRs
        tags: ghcr.io/amazeeio/opensearch:pr${{ github.event.pull_request.number }}-${{ needs.imagetag.outputs.version }}
